import os
import time

from google import genai
from google.genai import errors


# Create Gemini client using the GEMINI_API_KEY
client = genai.Client(
    api_key=os.environ.get("GEMINI_API_KEY")
)

GEMINI_MODEL = "gemini-3.8-flash"


def build_investigation_prompt(
    prediction: str,
    confidence: float,
    top_features: list,
    risk: str
):
    """
    Build the investigation prompt sent to Gemini.
    """

    feature_lines = []

    for item in top_features:
        feature_lines.append(
            f"- {item['feature']}: "
            f"value={item['value']}, "
            f"model_importance={item['importance']:.6f}"
        )

    features_text = "\n".join(feature_lines)

    prompt = f"""
You are a network security investigation assistant.

A traditional Random Forest Network Intrusion Detection System
has analyzed a network flow.

Model prediction: {prediction}
Model confidence: {confidence * 100:.2f}%
Risk level: {risk}

Important model features:
{features_text}

Your task is to explain this alert to a human security analyst.

Provide:
1. A short investigation summary.
2. The important observed network characteristics.
3. Why the model may consider the flow suspicious or benign.
4. The uncertainty or limitations of the prediction.
5. One recommended analyst verification step.

Important rules:
- Do not claim that one feature alone proves an attack.
- Do not invent missing network information.
- Treat the Random Forest prediction as evidence, not absolute truth.
- Clearly distinguish observed values from your interpretation.
- Keep the explanation concise and suitable for a security analyst.
"""

    return prompt.strip()


def build_fallback_explanation(
    prediction: str,
    confidence: float,
    top_features: list,
    risk: str
):
    """
    Build a deterministic explanation when Gemini is unavailable.

    This is NOT generated by an LLM.
    """

    feature_names = [
        item["feature"]
        for item in top_features[:3]
    ]

    features_text = ", ".join(feature_names)

    if prediction == "ATTACK":
        summary = (
            f"The Random Forest classified this network flow as "
            f"ATTACK with {confidence * 100:.2f}% confidence."
        )

        interpretation = (
            f"The model's globally important features include "
            f"{features_text}. These observed features provide "
            f"supporting evidence for the model's decision, but no "
            f"single feature independently proves that the flow is malicious."
        )

        verification = (
            "An analyst should verify the flow using additional "
            "network context such as source/destination behavior, "
            "related flows, and known attack indicators."
        )

    else:
        summary = (
            f"The Random Forest classified this network flow as "
            f"BENIGN with {confidence * 100:.2f}% confidence."
        )

        interpretation = (
            f"The model's globally important features include "
            f"{features_text}. These values are consistent with "
            f"the model's benign classification, but the prediction "
            f"should still be interpreted as model evidence rather than proof."
        )

        verification = (
            "An analyst should verify that there are no related "
            "alerts or unusual communication patterns associated "
            "with this flow."
        )

    return (
        f"{summary} "
        f"Risk level: {risk}. "
        f"{interpretation} "
        f"{verification}"
    )


def investigate_alert(
    prediction: str,
    confidence: float,
    top_features: list,
    risk: str
):
    """
    Send the Random Forest investigation context to Gemini.

    Transient Gemini errors such as 503 are retried.
    If Gemini remains unavailable, a deterministic fallback
    explanation is returned so that NIDS detection continues
    to work.
    """

    prompt = build_investigation_prompt(
        prediction=prediction,
        confidence=confidence,
        top_features=top_features,
        risk=risk
    )

    max_attempts = 3
    delays = [2, 5]

    for attempt in range(max_attempts):

        try:
            response = client.models.generate_content(
                model=GEMINI_MODEL,
                contents=prompt
            )

            return {
                "status": "SUCCESS",
                "explanation": response.text.strip()
            }

        except errors.ServerError as error:

            # Retry temporary server problems such as HTTP 503.
            if attempt < max_attempts - 1:
                time.sleep(delays[attempt])
                continue

            return {
                "status": "FALLBACK",
                "explanation": build_fallback_explanation(
                    prediction=prediction,
                    confidence=confidence,
                    top_features=top_features,
                    risk=risk
                ),
                "reason": (
                    "Gemini is temporarily unavailable. "
                    "Fallback explanation generated locally."
                ),
                "error": str(error)
            }

        except errors.ClientError as error:

            # Authentication, invalid requests, quota, etc.
            return {
                "status": "FALLBACK",
                "explanation": build_fallback_explanation(
                    prediction=prediction,
                    confidence=confidence,
                    top_features=top_features,
                    risk=risk
                ),
                "reason": (
                    "Gemini could not process the request. "
                    "Fallback explanation generated locally."
                ),
                "error": str(error)
            }

        except Exception as error:

            # Unexpected errors should not break NIDS detection.
            return {
                "status": "FALLBACK",
                "explanation": build_fallback_explanation(
                    prediction=prediction,
                    confidence=confidence,
                    top_features=top_features,
                    risk=risk
                ),
                "reason": (
                    "Gemini investigation failed unexpectedly. "
                    "Fallback explanation generated locally."
                ),
                "error": str(error)
            }